export const Films = [
  {
    id: 1,
    title: "Trò chơi gọi hồn 2  ",
    state: "",
    type: "Phim kinh dị",
    duration: "1g 39ph",
    director: "Mike Flanagan",
    actor:
      "Elizabeth Reaser, Annalise Basso, Henry Thomas, Lulu Wilson, Parker Mack, Kate Siegel, Doug Jones, Sam Anderson, Eve Gordon",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABbX3GRZvMQ1CtZ2K-KCsoljytLmeZ5jNBKamwQoETJEnp0Fbh7LOX4UDgsaq8wIAPzKFf-EFCG9sLeS0FQeqp5xQx36Tsaa73BU.webp?r=8e7",
    trailerURL: "https://www.youtube.com/watch?v=PTnU4jg93E4",
    description:
      "Tại California, vào những năm 1960, con gái một bà đồng rởm toan gọi hồn người cha quá cố qua Bàn cầu cơ nhưng lại vô tình giải phóng quỷ dữ.",
  },
  {
    id: 2,
    title: "Day Shift: Vỏ bọc thợ săn",
    state: "trending",
    type: "Phim kinh dị",
    duration: "1g 53ph",
    director: "JJ Perry",
    actor:
      "Jamie Foxx, Dave Franco, Natasha Liu Bordizzo, Meagan Good, Karla Souza, Steve Howey, Scott Adkins, Oliver Masucci, Snoop Dogg, Eric Lange, Peter Stormare, Zion Broadnax",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2F1.jpg?alt=media&token=5d53100e-bb28-45a6-9ea2-dbb8e32e3c73&_gl=1*1o3831a*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTQ2NDg3MC4xOS4xLjE2ODU0NjQ4NzQuMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=Xetxfi3EVXs",
    description:
      "Một thợ săn ma cà rồng ở Los Angeles có một tuần để kiếm tiền đóng học phí và niềng răng cho con mình. Thời buổi này, việc cố gắng kiếm sống lại có thể khiến anh toi đời.",
  },
  {
    id: 3,
    title: "Sói Viking",
    state: "trending",
    type: "Phim kinh dị",
    duration: "1g 38ph",
    director: "Stig Svendsen",
    actor:
      "Elli Müller Osborne, Liv Mjönes, Arthur Hakalahti, Mia Fosshaug Laubacher, Vidar Magnussen, Sjur VatneBrean, Øyvind Brandtzæg",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2FS%C3%B3i%20Viking.jpg?alt=media&token=8a5c1c02-6e16-4ad8-8cbf-2d450e697032&_gl=1*246e04*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTQ2NDg3MC4xOS4xLjE2ODU0NjUwNTMuMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=6sxnOLRGkhw",
    description:
      "Sau khi chứng kiến vụ án mạng kỳ dị tại một bữa tiệc ở thị trấn mới của mình, cô nàng tuổi teen nọ bắt đầu nhìn thấy những ảo ảnh kỳ lạ và có những ham muốn kỳ quái.",
  },
  {
    id: 4,
    title: "Ma cây",
    state: "",
    type: "Phim kinh dị",
    duration: "1g 31ph",
    director: "Fede Alvarez",
    actor:
      "Jane Levy, Shiloh Fernandez, Lou Taylor Pucci, Jessica Lucas, Elizabeth Blackmore, Phoenix Connolly, Jim McLarty, Sian Davis, Stephen Butterworth, Karl Willetts",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2FMa%20c%C3%A2y.webp?alt=media&token=8c75859d-83ea-438d-a4e0-e591713a1720&_gl=1*1hbtujs*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTQ2NDg3MC4xOS4xLjE2ODU0NjUzMjcuMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=5F3z-uXg63I",
    description:
      "Trong bản làm lại phim kinh dị kinh điển của Sam Raimi này, một nhóm bạn phát hiện ra một cuốn sách tà ác và vô tình giải phóng bầy quỷ khát máu.",
  },
  {
    id: 5,
    title: "Gương quỷ",
    state: "trending",
    type: "Phim kinh dị",
    duration: "1g 51ph",
    director: "Alexandre Aja",
    actor:
      "Kiefer Sutherland, Paula Patton, Cameron Boyce, Erica Gluck, Amy Smart, Mary Beth Peil, John Shrapnel, Jason Flemyng, Tim Ahern, Julian Glover",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2FG%C6%B0%C6%A1ng%20qu%E1%BB%B7.webp?alt=media&token=e9061fe4-038e-4345-a5a7-d7d36514c996&_gl=1*1bzymrv*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTQ2NDg3MC4xOS4xLjE2ODU0NjU0NjguMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=hfXzyrUzakg",
    description:
      "Đang làm bảo vệ ca đêm, một cựu cảnh sát đầy trăn trở phát hiện ra những ác linh ám các tấm gương ở một trung tâm mua sắm bị hỏa hoạn tàn phá.",
  },
  {
    id: 6,
    title: "Bạch Tuyết: Câu chuyện kinh hoàng",
    state: "",
    type: "Phim kinh dị",
    duration: "1g 40ph",
    director: "Michael Cohn",
    actor:
      "Sigourney Weaver, Sam Neill, Gil Bellows, Taryn Davis, Brian Glover, David Conrad, Monica Keena, Anthony Brophy, Frances Cuka, Chris Bauer",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2FB%E1%BA%A1ch%20Tuy%E1%BA%BFt%20-%20C%C3%A2u%20chuy%E1%BB%87n%20kinh%20ho%C3%A0ng.webp?alt=media&token=39a14760-0801-4fc0-be67-7a1e1fe5a77d&_gl=1*ih9on5*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTQ2NDg3MC4xOS4xLjE2ODU0NjU1OTkuMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=yRXReldV5gQ",
    description:
      "Bị cuốn vào vòng xoáy tội ác sau nỗi mất mát bi thảm, một nữ quý tộc ích kỷ triệu hồi tà thuật để cố gắng trừ khử cô con gái riêng trẻ trung và sôi nổi của mình.",
  },
  {
    id: 7,
    title: "Xác ướp",
    state: "trending",
    type: "Phim kinh dị",
    duration: "1g 50ph",
    director: "Alex Kurtzman",
    actor:
      "Tom Cruise, Annabelle Wallis, Sofia Boutella, Russell Crowe, Jake Johnson, Courtney B. Vance, Marwan Kenzari, Simon Atherton, Stephen Thompson, James Arama",
    img: "https://firebasestorage.googleapis.com/v0/b/lab-film-fer201m.appspot.com/o/H%C3%ACnh%20%E1%BA%A3nh%20c%C3%A1c%20b%E1%BB%99%20phim%20kinh%20d%E1%BB%8B%2Fx%C3%A1c%20%C6%B0%E1%BB%9Bp.webp?alt=media&token=0c14fddc-d5dd-4e87-a1c5-55fd9a22d395&_gl=1*lgn45l*_ga*MTU1OTk0NzM3OC4xNjgzNTA1MDE2*_ga_CW55HF8NVT*MTY4NTUyMjY3NS4yMS4xLjE2ODU1MjI2ODAuMC4wLjA.",
    trailerURL: "https://www.youtube.com/watch?v=C8sOvCS6AA4",
    description:
      "Một người lính truy tìm kho báu đánh thức một công chúa Ai Cập cổ đại. Nàng đã chờ đợi hàng thế kỷ để trả thù một thế giới đối xử tệ với mình.",
  },
  {
    id: 8,
    title: "Hiệp sĩ áo đen",
    state: "trending",
    type: "Phim Hàn Quốc",
    duration: "6 tập",
    director: "Cho Ui Seok, Shin Yeon Ju, Kim Hyun Deok",
    actor: "Kim Woo Bin, Song Seung Heon, Kang You Seok, Esom",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABQePvGZStww77jN0R-1Cq4LS1WEQmrhBpk29SURlRFW_KyyerG6GYDx0j1g-QP0sw3Y5yEikuVXzMk3GqNj2KwBZRJwko7_yeJSXcxe9UePomoW-PoVQSHnKoDbG4nN_T6ZHjbEOuBAOLJvTWK8EyeiMWedZOsZdiD8ekLQObeOK5CKmLKuAOsl4i0pd7Ok.jpg?r=9bb",
    trailerURL: "https://www.youtube.com/watch?v=pQh775SP_dA",
    description:
      "Ở tương lai tăm tối bị ô nhiễm không khí tàn phá, chuyện sống còn của loài người phụ thuộc vào nhóm Hiệp sĩ áo đen và họ khác xa những người giao hàng bình thường.",
  },
  {
    id: 9,
    title: "Bác sĩ Cha",
    state: "trending",
    type: "Phim Hàn Quốc",
    duration: "16 tập",
    director: "Kim Dae Jin, Jung Yeo Rang",
    actor: "Uhm Jung Hwa, Kim Byong Chul, Myung Se Bin, Min Woo Hyuk",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABdrZhiB_HEqW-PbV9O2_t6Jf3HVmsDt9Sj55Cdo0J7R8DtbNoHyrcfbfx_8HyMYce8oM_qTRRonvNF9c5pYdcXeFhDRRhfRcRvZ5VFt7a9JncAoDe_0tzQWTr_5OEWi0YarqsK7PUZ3RyQ7VdXi1n25A_duVER_PoRgkHf_DbTCpeuHjPE-RB0cDx6kcQQY4ZOb5DZUNBVQlaG5SGll91GYWfD6DP6BoMEnni-3juI40IsAmzBkITXLV1taMF7etpES9jfvh6uA0ogpabdkNJ7hwWOoDCY0SZIcVDapDQULmx-6yjy8ABtP-PfCW0ZrLnS58nYR4bkDtmmMUMvgz0Q9aY0BbUrEGaSkl9cqClhmvqL_k3r2bG86v7TddPmyLZ3NVMCZnkbj-fF9m3y-V_Sv66KljBmyWS7PEnvBhWHZGbbp6Dv5ELTEh8FXyq2Hvm8GCm0A2Ur302sMaLtXCjemSGfj3I-SrO-oa1nwjphAsoY5AIU8dpKSuySAa7A6QQQ.jpg?r=402",
    trailerURL: "https://www.youtube.com/watch?v=AY-V1rKkCzQ",
    description:
      "Hai mươi năm sau khi rời bỏ nghề y, một bà nội trợ trở lại với tư cách là bác sĩ nội trú năm nhất và chật vật tìm chỗ đứng trong một công việc đầy những bất ngờ.",
  },
  {
    id: 10,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 11,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 12,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 13,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 14,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 15,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
  {
    id: 16,
    title: "Tân phong thần: Na Tra trùng sinh",
    state: "",
    type: "Phim Anime",
    duration: "1g 50ph",
    director: "Triệu Tễ",
    actor: "Dương Thiên Tường, Trương Hách, Tuyên Hiểu Minh, Lí Thi Minh",
    img: "https://occ-0-325-395.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWemk5eMuCOKgBlC_o__WoQZAIF-M3rUljVK79eeOuZQ6NiGMc6ENnOMrm3lSP4j8_3Z1BdH4ouwmu1vlGbF-4x4lkXiv2EPISnyH4kLfzay8tRTZhNRKIx9jkNMJMHRpXy9.jpg?r=9b8",
    trailerURL: "https://www.youtube.com/watch?v=BvOAAM0ZFQM",
    description:
      "Trong cuộc sống của một người giao hàng bình thường kiêm tín đồ đua xe, Na Tra chạm trán những kẻ thù cũ và phải tìm lại năng lực của mình để bảo vệ những người thân yêu.",
  },
];
